# Generated by Django 4.2.1 on 2023-05-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawl.product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
