# Generated by Django 4.2.1 on 2023-05-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_alter_oderitem_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
