# Generated by Django 4.2.1 on 2023-05-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_product_brand_name_product_discount_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_seller',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
